{
  "params_network": {
    "memb_net": {
      "inNodeFeatures": 10,
      "nNodeFeatEmbedding": 24,
      "outNodeFeatures": 10,
      "nEdgeFeatures": 7,
      "ker_width": 8
    },
    "flow_net": {
      "inNodeFeatures": 4,
      "nNodeFeatEmbedding": 24,
      "outNodeFeatures": 4,
      "nEdgeFeatures": 14,
      "ker_width": 4
    },
    "attn_dim": 24,
    "nlayers": 4,
    "time_embedding_dim": 8
  },

  "params_training": {
    "epochs": 101,
    "learning_rate": 0.004,
    "scheduler_step": 500,
    "scheduler_gamma": 0.5,
    "validation_frequency": 100,
    "save_frequency": 100,
    "flow_weight": 0.8,
    "memb_weight": 0.2
  },

  "params_data": {
    "batch_size": 3,
    "ntsteps": 1,
    "val_split": 0.3
  },
  
  "train_radius": {
    "radius_flow": 0.08,
    "radius_memb": 0.04,
    "radius_cross": 0.04
  }
}